### ISSUE TITLE
YARN 0.27 causes command version check in analyzer to fail

### ISSUE THREAD

**Issue by iamwillbar** [heremaps/oss-review-toolkit#129]
Here is the output from `analyzer`:

```
The following package managers are activated:
        Gradle, Maven, SBT, NPM, PIP
Scanning project path:
        /app
NPM projects found in:
        oss-attribution-builder/package.json
17:46:30.994 [main] INFO  com.here.ort.util.UtilsKt$log$1 - Running 'npm --version'...
17:46:30.999 [main] DEBUG com.here.ort.util.UtilsKt$log$1 - Keeping temporary files:
17:46:31.000 [main] DEBUG com.here.ort.util.UtilsKt$log$1 - /tmp/npm6011353000025587699.stdout
17:46:31.000 [main] DEBUG com.here.ort.util.UtilsKt$log$1 - /tmp/npm6832287346807849534.stderr
17:46:31.242 [main] INFO  com.here.ort.util.UtilsKt$log$1 - Running 'yarn --version'...
17:46:31.242 [main] DEBUG com.here.ort.util.UtilsKt$log$1 - Keeping temporary files:
17:46:31.243 [main] DEBUG com.here.ort.util.UtilsKt$log$1 - /tmp/yarn2289262920421819612.stdout
17:46:31.243 [main] DEBUG com.here.ort.util.UtilsKt$log$1 - /tmp/yarn792803821624333627.stderr
Exception in thread "main" com.vdurmont.semver4j.SemverException: Invalid version (no patch version): 0.27
        at com.vdurmont.semver4j.Semver.<init>(Semver.java:81)
        at com.vdurmont.semver4j.Semver.<init>(Semver.java:20)
        at com.vdurmont.semver4j.Requirement.isSatisfiedBy(Requirement.java:515)
        at com.here.ort.util.ProcessCaptureKt.checkCommandVersion(ProcessCapture.kt:117)
        at com.here.ort.util.ProcessCaptureKt.checkCommandVersion$default(ProcessCapture.kt:114)
        at com.here.ort.analyzer.managers.NPM.prepareResolution(NPM.kt:116)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:73)
        at com.here.ort.analyzer.Main$main$5.accept(Main.kt:247)
        at com.here.ort.analyzer.Main$main$5.accept(Main.kt:52)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.here.ort.analyzer.Main.main(Main.kt:245)
```

If I run `yarn --version` here is the output:
```
0.27
```

**Comment by sschuberth** [comment]
Thanks a lot for the report! While yarn 0.27 is not as old as it's version number suggests, I'd actually consider it to be a bug in yarn to not report a semver for its version as usual in the NPM world. Anyway, this should be easy to fix.

**Comment by iamwillbar** [comment]
I agree, but depending on all tools to return good semver values feels
optimistic. I'd apply the IETF RFC adage of "be strict when sending and
tolerant when receiving" here (https://tools.ietf.org/html/rfc1958#section-3
).
