### ISSUE TITLE
IndexOutOfBoundsException when reading .npmrc file

### ISSUE THREAD

**Issue by kallesoranko** [heremaps/oss-review-toolkit#1679]
I get this error when running Analyzer over an NPM project:
```
15:31:33.359 ERROR - Resolving dependencies for 'package.json' in 'D:\tfs\NEO\dev02\src\idm\Presentation\UI\UX\package.json', failed with: Index: 1, Size: 1
15:31:33.359 ERROR - java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1$1.invoke(Npm.kt:187)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1$1.invoke(Npm.kt:75)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:160)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:166)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine$default(FileReadWrite.kt:164)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1.invoke(Npm.kt:186)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1.invoke(Npm.kt:75)
        at com.here.ort.utils.OkHttpClientHelper.execute(OkHttpClientHelper.kt:105)
        at com.here.ort.analyzer.managers.Npm.parseInstalledModules(Npm.kt:270)
        at com.here.ort.analyzer.managers.Npm.resolveDependencies(Npm.kt:162)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
        at com.here.ort.analyzer.Analyzer.analyze(Analyzer.kt:110)
        at com.here.ort.commands.AnalyzerCommand.runCommand(AnalyzerCommand.kt:156)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.runCommand(Main.kt:112)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.run(Main.kt:95)
        at com.here.ort.Main.main(Main.kt:75)
```
(btw. stacktrace printing is not available by default)

And in my `~/.npmrc` I have:
```
proxy=null
https-proxy=null
```

**Comment by kallesoranko** [comment]
As a workaround I commented out `stashDirectories(... ` and `installDependencies(workingDir)` lines.
It also would be great to be able to use one's internal NPM registry instead of `https://registry.npmjs.org`

**Comment by sschuberth** [comment]
Thanks for the report, a fix is underway.

> It also would be great to be able to use one's internal NPM registry instead of `https://registry.npmjs.org`.

Please file a separate issue for this. In general, our `npm install` part respects the registry as configured in `.npmrc`, but our querying of additional meta-data currently always uses "registry.npmjs.org".

**Comment by kallesoranko** [comment]
nice, thanks for the lightning fast response ⚡️ 👍

**Comment by sschuberth** [comment]
@kallesoranko, if you don't mind double-checking, please verify that the fix which was just merged to `master` actually fixes your problem.

**Comment by kallesoranko** [comment]
Pulled the latest and tested this again, but while having the same contents in `.npmrc` I now get:
```
java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
        at com.here.ort.utils.OkHttpClientHelper.applyProxySettingsFromUrl(OkHttpClientHelper.kt:72)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1$1.invoke(Npm.kt:198)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1$1.invoke(Npm.kt:75)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:160)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:166)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine$default(FileReadWrite.kt:164)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1.invoke(Npm.kt:187)
        at com.here.ort.analyzer.managers.Npm$applyProxySettingsFromNpmrc$1.invoke(Npm.kt:75)
        at com.here.ort.utils.OkHttpClientHelper.execute(OkHttpClientHelper.kt:116)
        at com.here.ort.analyzer.managers.Npm.parseInstalledModules(Npm.kt:271)
        at com.here.ort.analyzer.managers.Npm.resolveDependencies(Npm.kt:163)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
        at com.here.ort.analyzer.Analyzer.analyze(Analyzer.kt:110)
        at com.here.ort.commands.AnalyzerCommand.runCommand(AnalyzerCommand.kt:156)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.runCommand(Main.kt:112)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.run(Main.kt:95)
        at com.here.ort.Main.main(Main.kt:75)
```
and if I remove proxy settings completely, I get:
```
java.lang.IllegalStateException: url.userInfo must not be null
        at com.here.ort.utils.OkHttpClientHelper$applyProxySettingsFromUrl$1.authenticate(OkHttpClientHelper.kt:75)
        at okhttp3.internal.connection.RealConnection.createTunnelRequest(RealConnection.kt:483)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:231)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:170)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.here.ort.utils.OkHttpClientHelper.execute(OkHttpClientHelper.kt:120)
        at com.here.ort.analyzer.managers.Npm.parseInstalledModules(Npm.kt:271)
        at com.here.ort.analyzer.managers.Npm.resolveDependencies(Npm.kt:163)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
        at com.here.ort.analyzer.Analyzer.analyze(Analyzer.kt:110)
        at com.here.ort.commands.AnalyzerCommand.runCommand(AnalyzerCommand.kt:156)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.runCommand(Main.kt:112)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.run(Main.kt:95)
        at com.here.ort.Main.main(Main.kt:75)
```
so seems like the bug is not resolved yet.

**Comment by sschuberth** [comment]
Sorry @kallesoranko for messing this up, I'm on it.

**Comment by sschuberth** [comment]
@kallesoranko, please give `master` another try.

**Comment by kallesoranko** [comment]
Re-tested, but still not working. Output is now same when setting `(https-)proxy=null` or is proxies not set at all:
```
java.io.IOException: Unexpected response code for CONNECT: 400
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:447)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:235)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:170)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.here.ort.utils.OkHttpClientHelper.execute(OkHttpClientHelper.kt:126)
        at com.here.ort.analyzer.managers.Npm.parseInstalledModules(Npm.kt:272)
        at com.here.ort.analyzer.managers.Npm.resolveDependencies(Npm.kt:163)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
        at com.here.ort.analyzer.Analyzer.analyze(Analyzer.kt:110)
        at com.here.ort.commands.AnalyzerCommand.runCommand(AnalyzerCommand.kt:156)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.runCommand(Main.kt:112)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.run(Main.kt:95)
        at com.here.ort.Main.main(Main.kt:75)
```

**Comment by sschuberth** [comment]
> Output is now same when setting `(https-)proxy=null` or is proxies not set at all:

Well, isn't that expected? If `(https-)proxy=null` then no proxy settings are applied.

Could you share some more context about your environment, as I'm not getting why to set `(https-)proxy=null` in the first place:

* If your environment requires a proxy to be used, why don't you set it?
* If your environment does not require a proxy to be used, why do you set `(https-)proxy=null` instead of just omitting the configuration?
* Do you have the `http_proxy` / `https_proxy` environment variables set?

**Comment by kallesoranko** [comment]
I am running ORT in an environment which is behind a corporate proxy. We are also using internal Artifactory as an NPM registry and Maven/Gradle artifact repository. For NPM we want to set `(https-)proxy=null` when we are installing dependencies, since registry is in the intranet, on the other hand ORT queries `https://registry.npmjs.org`, so we need proxy for that. I have understood that connection to `https://registry.npmjs.org` is done using `OkHttpClient` and for that we set `http_proxy` and `https_proxy` environment variables. That said, omitting `(https-)proxy=null` completely from `.npmrc` sounds reasonable, but I get same as above when I leave those out:
```
java.io.IOException: Unexpected response code for CONNECT: 400
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:447)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:235)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:170)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.here.ort.utils.OkHttpClientHelper.execute(OkHttpClientHelper.kt:126)
        at com.here.ort.analyzer.managers.Npm.parseInstalledModules(Npm.kt:272)
        at com.here.ort.analyzer.managers.Npm.resolveDependencies(Npm.kt:163)
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
        at com.here.ort.analyzer.Analyzer.analyze(Analyzer.kt:110)
        at com.here.ort.commands.AnalyzerCommand.runCommand(AnalyzerCommand.kt:156)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.runCommand(Main.kt:112)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:53)
        at com.here.ort.Main.run(Main.kt:95)
        at com.here.ort.Main.main(Main.kt:75)
```
For testing purposes I also tried to set the proxies in `.npmrc` file and surprisingly I got the same output, so not sure what is going on since my Kotlin skills are not so up-to-date.

**Comment by sschuberth** [comment]
> We are also using internal Artifactory as an NPM registry [...], on the other hand ORT queries https://registry.npmjs.org, so we need proxy for that.

*That* was the important bit of information. This "split" of proxy-configurations is currently not supported: Our implementation either uses the proxy defined in `.npmrc` for everything (running `npm install` and accessing `registry.npmjs.org` via OkHttp), or no proxy is used at all if none is defined in `.npmrc`. So you're requesting a new feature, and I'll think about how to do the implementation.

**Comment by sschuberth** [comment]
@kallesoranko, can you please try if https://github.com/heremaps/oss-review-toolkit/pull/1691 solved your issue?

**Comment by kallesoranko** [comment]
@sschuberth I deployed https://github.com/heremaps/oss-review-toolkit/pull/1691 and re-tested and now analyzer is working correctly without having to change the proxy settings. Thanks for the patch and sorry about the inconvenience.

**Comment by sschuberth** [comment]
There was no incontinence involved! Thanks for making ORT a better product by helping to address issues with it.
