### ISSUE TITLE
MismatchedInputException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by kallesoranko** [heremaps/oss-review-toolkit#1728]
Came across this exception, which is currently blocking the usage of Scanner. This happens after scanning stage and this is not dependent on a component, but happens with different components on consecutive runs.

```
b"17:04:29.846 INFO  - Running 'C:\\Users\\z00407wp\\scancode-toolkit-3.0.2\\scancode.bat --version' in 'C:\\Users\\z00407wp\\ksoranko\\oss-review-toolkit\\cli'...\r\n"
b'17:04:44.990 DEBUG - ScanCode version 3.0.2\r\n'
b'17:04:44.990 DEBUG - \r\n'
b'17:04:44.990 DEBUG - \r\n'
b"17:04:44.998 INFO  - Using stored scan result for 'NPM::abab:2.0.0' found at 'C:\\Users\\z00407wp\\.ort\\scanner\\scan-results\\NPM\\unknown\\abab\\2.0.0\\scan-results.yml'.\r\n"
b"17:04:45.302 INFO  - Successfully added scan result for 'NPM::abab:2.0.0' to 'C:\\Users\\z00407wp\\.ort\\scanner\\scan-results\\NPM\\unknown\\abab\\2.0.0\\scan-results.yml'.\r\n"
b'17:04:45.302 INFO  - Finished scanning NPM::abab:2.0.0 (2/1201).\r\n'
b'\r\n'
b'> Task :cli:run FAILED\r\n'
b'\n'
b'Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.\n'
b"Use '--warning-mode all' to show the individual deprecation warnings.\n"
b'See https://docs.gradle.org/5.6/userguide/command_line_interface.html#sec:command_line_warnings\r\n'
b'41 actionable tasks: 19 executed, 22 up-to-date\r\n'
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2921)
        at com.here.ort.scanner.storages.LocalFileStorage.readFromStorage(LocalFileStorage.kt:84)
        at com.here.ort.scanner.ScanResultsStorage.read(ScanResultsStorage.kt:98)
        at com.here.ort.scanner.storages.FileBasedStorage.readFromStorage(FileBasedStorage.kt:36)
        at com.here.ort.scanner.ScanResultsStorage.read(ScanResultsStorage.kt:118)
        at com.here.ort.scanner.LocalScanner.readFromStorage(LocalScanner.kt:250)
        at com.here.ort.scanner.LocalScanner.access$readFromStorage(LocalScanner.kt:70)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$1.invokeSuspend(LocalScanner.kt:168)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_221\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 44s
```

**Comment by sschuberth** [comment]
This looks like your local scan storage is corrupt. I highly recommend to use another more sophisticated storage solution, preferably the upcoming [Postgres storage backend](https://github.com/heremaps/oss-review-toolkit/pull/1718). As a work-around, if you don't mind losing your scan storage (which means packages need to be re-scanned), delete / rename your `~/.ort/scanner/scan-results` directory to see if that helps.

**Comment by kallesoranko** [comment]
It is highly possible that local storage is corrupted and it is causing this error. Background for this is that I have this NPM project with over 1200 components and I am working to get it scanned with ORT. I've had quite  hard time with this because https://github.com/heremaps/oss-review-toolkit/issues/1406 keeps happening. So basically what I have done is that when scan crashes I just change I just point scanner result folder to a new one. I have even written a python script for this,  but even with that it is practically impossible to scan the project, since that crash happens after every few components. 

That said it is really good news that you are working on a Postgres storage backend solution. Also I noticed that you have updated the version of ScanCode and now after running the scanner for an hour, it has went smoothly this far.

I guess this ticket can be closed, since bug is gone after renaming `~/.ort/scanner/scan-results`

**Comment by kallesoranko** [comment]
Found different bug with same effect, created https://github.com/heremaps/oss-review-toolkit/issues/1731
