### ISSUE TITLE
Scanner crashes at random points

### ISSUE THREAD

**Issue by kallesoranko** [heremaps/oss-review-toolkit#1731]
Scanner seems to crash after processing few components with error:
```
Run pre-scans...
 Run pre-scan: ignore...
Scan files for: info, licenses, copyrights with 3 process(es)...
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\.editorconfig
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\index.js
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\license
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\package.json
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\readme.md
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\screenshot.png
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\test.js
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\.jshintrc
Scanned: C:\Users\z00407wp\Desktop\ORT\NEO\dev02\idm-ux\scanner2\downloads\NPM\unknown\ansi-styles\2.2.1\.travis.yml
Removing temporary files...done.
Traceback (most recent call last):
  File "C:\Users\z00407wp\scancode-toolkit-3.0.2\Scripts\scancode-script.py", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "C:\Users\z00407wp\scancode-toolkit-3.0.2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\z00407wp\scancode-toolkit-3.0.2\src\scancode\utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "C:\Users\z00407wp\scancode-toolkit-3.0.2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\z00407wp\scancode-toolkit-3.0.2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\z00407wp\scancode-toolkit-3.0.2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\z00407wp\scancode-toolkit-3.0.2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\z00407wp\scancode-toolkit-3.0.2\src\scancode\cli.py", line 752, in scancode
    quiet=quiet, verbose=verbose, kwargs=kwargs,
  File "c:\users\z00407wp\scancode-toolkit-3.0.2\src\scancode\cli.py", line 929, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "c:\users\z00407wp\scancode-toolkit-3.0.2\src\scancode\cli.py", line 1075, in scan_codebase
    pool.terminate()
  File "c:\python27\Lib\multiprocessing\pool.py", line 465, in terminate
    self._terminate()
  File "c:\python27\Lib\multiprocessing\util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "c:\python27\Lib\multiprocessing\pool.py", line 513, in _terminate_pool
    p.terminate()
  File "c:\python27\Lib\multiprocessing\process.py", line 137, in terminate
    self._popen.terminate()
  File "c:\python27\Lib\multiprocessing\forking.py", line 312, in terminate
    _subprocess.TerminateProcess(int(self._handle), TERMINATE)
WindowsError: [Error 5] Access is denied

Exception in thread "main" java.lang.NullPointerException
        at com.here.ort.scanner.scanners.ScanCode.getFileCount(ScanCode.kt:356)
        at com.here.ort.scanner.scanners.ScanCode.generateSummary$scanner(ScanCode.kt:360)
        at com.here.ort.scanner.scanners.ScanCode.scanPath(ScanCode.kt:324)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:306)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:70)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$2.invokeSuspend(LocalScanner.kt:183)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.NullPointerException
                ... 15 more

> Task :cli:run FAILED
```

I am using master branch at `d0eac47b92950375f808e54616fdf95e56d33089`

**Comment by sschuberth** [comment]
The NPE in ORT seems to be caused by a crash in ScanCode, so please report this to ScanCode instead.

**Comment by oova** [comment]
Is there a way to set the number of processes used by ScanCode?
I'm asking because I get the same `WindowsError: [Error 5] Access is denied` issue on my machine when I run ScanCode with the default number of processes (7 in my case ), but I do __not__ see this error when I run with 8 processes.

**Comment by sschuberth** [comment]
@oova, you can override the [default configuration options](https://github.com/heremaps/oss-review-toolkit/blob/4f817687be4cdee702210094230ee62a9fcb2795/scanner/src/main/kotlin/scanners/ScanCode.kt#L110-L112) passed to ScanCode by passing a [configuration file](https://github.com/heremaps/oss-review-toolkit/blob/4f817687be4cdee702210094230ee62a9fcb2795/cli/src/main/kotlin/OrtMain.kt#L70-L71) to ORT that contains a scanner-specific section. IIRC it should look something like this:

```hocon
ort {
  scanner {
    scanner {
      ScanCode {
        commandLineNonConfig = "--processes 8"
      }
    }
  }
}
```

I'm not 100% sure about the double nested "scanner" part... can you confirm @mnonnenmacher?

Anyway, I highly doubt the `Access is denied` error is related to the number of processes, and I believe it was just coincidence that you saw it going again with 8 processes.

**Comment by oova** [comment]
Thanks, the given configuration seems to work. Scancode is running with 8 processes and I have not seen an `Access is denied` error so far.
