### ISSUE TITLE
[scanner] DotNet  - AccessDeniedException

### ISSUE THREAD

**Issue by fb33** [heremaps/oss-review-toolkit#2072]
Hello,

I m running ORT on windows with a git bash in admin mode.
The scanner step failed without a result file.
I ve got this access denied error : 
```
08:09:16.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - ScanCode version 3.0.2
08:09:16.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
08:09:16.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
08:09:16.939 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Could not read scan results for 'nuget::Microsoft.AspNetCore.Authorization.Policy:2.0.0' from path 'nuget/unknown/Microsoft.AspNetCore.Authorization.Policy/2.0.0/scan-results.yml': FileNotFoundException: D:\Users\j.dupont\.ort\scanner\results\nuget\unknown\Microsoft.AspNetCore.Authorization.Policy\2.0.0\scan-results.yml (Le chemin d▒acc▒s sp▒cifi▒ est introuvable)
08:09:17.195 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'nuget::Microsoft.AspNetCore.Authorization.Policy:2.0.0' at path 'nuget/unknown/Microsoft.AspNetCore.Authorization.Policy/2.0.0/scan-results.yml'.
08:09:17.195 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning nuget::Microsoft.AspNetCore.Authorization.Policy:2.0.0 (6/209).
Exception in thread "main" java.nio.file.AccessDeniedException: C:\workspace\POCs\MOB_ORT\thesubstitute\src\my.project\reports\downloads\DotNet\unknown\my.project.csproj\unknown\.git\objects\pack\pack-598131a86f4c8d633a21b414c0eba26b499006c2.idx
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:128)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:128)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively$default(Extensions.kt:121)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:250)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:290)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:74)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:194)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
any idea? 

Regards

**Comment by sschuberth** [comment]
Do you maybe have TortoiseGit installed? I saw its shell extension locking `.git` directories in the past...

**Comment by fb33** [comment]
No TortoiseGit installed.
I can change the name of the idx file successfully, no process handle the file...

**Comment by sschuberth** [comment]
Renaming works even if the file is locked, that's an old trick on Windows. Could you please run e.g. https://lockhunter.com/ on the locked file if it happens again?

**Comment by fb33** [comment]
lockunter didn't find a lock

**Comment by sschuberth** [comment]
Very odd, so it's maybe not a locking but still a permission problem for some reason. How reliably can you reproduce the issue, does it happen every time?

**Comment by fb33** [comment]
it happens two successive times.
I'll try an other time after my current scan on a node project ends. :-)

**Comment by fb33** [comment]
an other execution confirm the error
```
Scanning done.
Summary:        info, licenses, copyrights with 7 process(es)
Errors count:   0
Scan Speed:     0.89 files/sec. 2.49 KB/sec.
Initial counts: 50 resource(s): 42 file(s) and 8 directorie(s)
Final counts:   49 resource(s): 42 file(s) and 7 directorie(s) for 117.63 KB
Timings:
  scan_start: 2019-12-20T143146.133000
  scan_end:   2019-12-20T143238.496000
  setup_scan:licenses: 5.04s
  setup: 5.04s
  scan: 47.22s
  total: 52.42s
Removing temporary files...done.

15:32:40.388 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'D:\Users\j.dupont\AppData\Local\Temp\ort3807041836551014856ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --version' in 'C:\workspace\POCs\MOB_ORT\oss-review-toolkit'...
15:32:53.936 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - ScanCode version 3.0.2
15:32:53.937 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
15:32:53.937 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
15:32:54.333 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'nuget::Autofac.Extensions.DependencyInjection:5.0.1' at path 'nuget/unknown/Autofac.Extensions.DependencyInjection/5.0.1/scan-results.yml'.
15:32:54.335 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning nuget::Autofac.Extensions.DependencyInjection:5.0.1 (2/209).
Exception in thread "main" java.nio.file.AccessDeniedException: C:\workspace\POCs\MOB_ORT\thesubstitute\src\my.project\reports\downloads\DotNet\unknown\my.project.csproj\unknown\.git\objects\pack\pack-598131a86f4c8d633a21b414c0eba26b499006c2.idx
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:128)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:128)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively$default(Extensions.kt:121)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:250)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:290)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:74)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:194)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by sschuberth** [comment]
We haven't seen this before, despite having done several thousands of scans. On the other hand, we're usually running scans on Linux. So I believe this is a Windows-specific thing plus maybe something about your setup, but for now I'm clueless.

**Comment by sschuberth** [comment]
@fb33, if you're willing to try something out, you may want to give my `force-delete-vcs` branch a try.

**Comment by fb33** [comment]
Ok, i'll checkout the `force-delete-vcs` branch and do the test

**Comment by sschuberth** [comment]
I'm pretty sure that fixes it because of what I read from the discussion at https://github.com/libgit2/libgit2sharp/issues/1354#issuecomment-277968633.

**Comment by fb33** [comment]
It works with the force-delete-vcs branch ! thanks

**Comment by sschuberth** [comment]
Great! Thanks again for reporting the issue and confirming the fix.
