### ISSUE TITLE
Scanning quits when trying to download from invalid URL

### ISSUE THREAD

**Issue by oova** [heremaps/oss-review-toolkit#2191]
When I scan the results of the analyzer, the scanning process will quit when sources for a dependency cannot be downloaded due to an invalid URL.

This is the stacktrace:

````
Exception in thread "main" org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of ls-remote command
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:218)
        at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:161)
        at com.here.ort.downloader.vcs.GitWorkingTree.listRemoteTags(GitWorkingTree.kt:116)
        at com.here.ort.downloader.WorkingTree.guessRevisionName(WorkingTree.kt:89)
        at com.here.ort.downloader.VersionControlSystem.download(VersionControlSystem.kt:261)
        at com.here.ort.downloader.VersionControlSystem.download$default(VersionControlSystem.kt:226)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:256)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:287)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:75)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.jgit.errors.NotSupportedException: URI not supported: file://author-name@github.com/author-name/mylib.git
        at org.eclipse.jgit.transport.Transport.open(Transport.java:561)
        at org.eclipse.jgit.transport.Transport.open(Transport.java:429)
        at org.eclipse.jgit.transport.Transport.open(Transport.java:308)
        at org.eclipse.jgit.transport.Transport.open(Transport.java:276)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:188)
````

As you can see, the analyser found a a VCS URL of the form `file://author-name@github.com/author-name/mylib.git` which cannot be used for downloading files. A `DownloadException` is not thrown in this case.

When I fix the URL to `https://github.com/author-name/mylib.git`, the scanner/downloader works as expected.

I have been advised to ping @sschuberth on this issue. ;-)

Thank you.
Uwe

**Comment by sschuberth** [comment]
That's interesting, could you please share both the processed and unprocessed VCS URLs from the analyzer result of this package?

**Comment by oova** [comment]
Here's the relevant part from the `analyzer-result.json`:
````
"vcs" : {
    "type" : "https",
    "url" : "//author-name@github.com/author-name/mylib.git",
    "revision" : "",
     "path" : ""
},
"vcs_processed" : {
    "type" : "Git",
    "url" : "file:////author-name@github.com/author-name/mylib.git",
    "revision" : "",
    "path" : ""
}
````

**Comment by sschuberth** [comment]
Thanks! Are the "author-name" and "mylib" parts replacements made by you? If so, what's the real GitHub project behind that package? I'm asking because that package's meta-data seems to be broken, and we should try to get it fixed upstream, if possible.

**Comment by sschuberth** [comment]
Also, `"type" : "https"` looks very wrong, that's not a valid VCS type in ORT. What kind of package is this, a Maven package? Or NPM maybe?

**Comment by oova** [comment]
You can replace "author-name" by "ben-manes" and "mylib.git" by "caffeine.git". It's a Maven package. I have seen the same issue with similar Maven packages originating from Github, though.

**Comment by sschuberth** [comment]
Thanks, which version of the *caffeine* package?

**Comment by sschuberth** [comment]
Also see my https://github.com/ben-manes/caffeine/pull/394.

**Comment by oova** [comment]
Thanks for taking care of this. For the record, I used _caffeine_ in version 2.8.0.

I will try to re-run the scanner with the latest code changes and check if the issue is gone.

**Comment by sschuberth** [comment]
FYI @oova, all of the [upstream fix](https://github.com/ben-manes/caffeine/pull/394) (for future releases of *caffeine*), the [improved error handling for JGit](https://github.com/heremaps/oss-review-toolkit/pull/2198) and the [fault-tolerant parsing of invalid Maven SCM tags](https://github.com/heremaps/oss-review-toolkit/pull/2199) have been merged now, so you should be good to go :wink:
