### ISSUE TITLE
Scanner crashes when trying to invoke 'hg' command

### ISSUE THREAD

**Issue by oova** [heremaps/oss-review-toolkit#2209]
I want to scan a Maven project with the following dependency:
```xml
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>1.25</version>
</dependency>  
```
The scanner crashes with the following stacktrace:
```
09:17:31.630 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored results found, scanning package Maven:org.yaml:snakeyaml:1.25 in thread 'ScanCode-1' (2/2).
09:17:31.640 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Trying to download source code for 'Maven:org.yaml:snakeyaml:1.25'.
09:17:31.647 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Trying to download 'Maven:org.yaml:snakeyaml:1.25' sources to '/ort/scans/ort-demo/downloads/Maven/org.yaml/snakeyaml/1.25' from VCS...
09:17:31.648 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Using VcsInfo(type=Mercurial, url=http://bitbucket.org/asomov/snakeyaml, revision=snakeyaml-1.25, resolvedRevision=null, path=).
09:17:31.819 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Detected VCS type 'Mercurial' from type name 'Mercurial'.
Exception in thread "main" java.io.IOException: Cannot run program "hg": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.here.ort.utils.ProcessCapture.<init>(ProcessCapture.kt:86)
        at com.here.ort.utils.ProcessCapture.<init>(ProcessCapture.kt:29)
        at com.here.ort.utils.ProcessCapture.<init>(ProcessCapture.kt:33)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:90)
        at com.here.ort.downloader.vcs.Mercurial.run(Mercurial.kt:40)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.getVersion(CommandLineTool.kt:99)
        at com.here.ort.downloader.vcs.Mercurial.getVersion(Mercurial.kt:40)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.getVersion$default(CommandLineTool.kt:97)
        at com.here.ort.downloader.vcs.Mercurial.getVersion(Mercurial.kt:50)
        at com.here.ort.downloader.VersionControlSystem$download$1.invoke(VersionControlSystem.kt:228)
        at com.here.ort.downloader.VersionControlSystem$download$1.invoke(VersionControlSystem.kt:37)
        at org.apache.logging.log4j.kotlin.SuppliersKt$asLog4jSupplier$1.get(Suppliers.kt:21)
        at org.apache.logging.log4j.util.LambdaUtil.getMessage(LambdaUtil.java:91)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1868)
        at org.apache.logging.log4j.kotlin.KotlinLogger.info(KotlinLogger.kt:355)
        at com.here.ort.downloader.VersionControlSystem.download(VersionControlSystem.kt:228)
        at com.here.ort.downloader.VersionControlSystem.download$default(VersionControlSystem.kt:226)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:240)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:287)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:75)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 30 more
```
The root cause seems to be the missing `hg` executable on my Linux machine. If I install the Mercurial package, the scan will run successfully.

Is an installed Mercurial package a prerequisite for the scanner to run successfully when at least one of the components to be scanned specifies Mercurial as its VCS? If so, is this documented somewhere?

Thanks
Uwe

**Comment by sschuberth** [comment]
> Is an installed Mercurial package a prerequisite for the scanner to run successfully when at least one of the components to be scanned specifies Mercurial as its VCS?

Yes. Funnily @blaumeiser-at-bosch just reported exactly the same to me yesterday :grinning: 

> If so, is this documented somewhere?

No directly, but somewhat indirectly by running the `ort requirements` command.

Anyway, I'll looking to a fix that makes ORT at least continue with other non-Mercurial packages.

**Comment by oova** [comment]
Thanks!
