### ISSUE TITLE
'dependencyManagement' Errors during the Analyzer Step

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2274]
Am I getting the errors below because those JARs are flat dir repositories?

**Error 1:**
```bash
Caused by: ModelBuildingException: 2 problems were encountered while building the effective model for org.glassfish.jaxb:jaxb-core:2.2.11
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ 
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ com.sun.xml.bind.mvn:jaxb-parent:2.2.11, /root/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind.mvn/jaxb-parent/2.2.11/9496f6747e6d5ab5da869941dea4143969122b91/jaxb-parent-2.2.11.pom, line 188, column 29
```
**Error 2:**
```bash
11:04:20.952 [analyzer-1] WARN  com.here.ort.analyzer.managers.utils.MavenLogger - Failed to build parent project for com.sun.xml.bind.mvn:jaxb-txw-parent:pom:2.2.11
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 497, column 32
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ line 188, column 29

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:207) ~[maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:342) ~[maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299) ~[maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.initParent(DefaultProjectBuilder.java:960) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:680) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:342) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.initParent(DefaultProjectBuilder.java:960) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:680) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:342) [maven-core-3.6.3.jar:3.6.3]
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299) [maven-core-3.6.3.jar:3.6.3]
        at com.here.ort.analyzer.managers.utils.MavenSupport$parsePackage$$inlined$let$lambda$1.invoke(MavenSupport.kt:517) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.utils.MavenSupport$parsePackage$$inlined$let$lambda$1.invoke(MavenSupport.kt:95) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.utils.MavenSupport.wrapMavenSession(MavenSupport.kt:608) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.utils.MavenSupport.parsePackage(MavenSupport.kt:516) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.utils.MavenSupport.parsePackage$default(MavenSupport.kt:494) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:265) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:287) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:287) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:287) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:287) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:287) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.parseDependency(Gradle.kt:287) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.access$parseDependency(Gradle.kt:67) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle$resolveDependencies$4.invoke(Gradle.kt:192) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle$resolveDependencies$4.invoke(Gradle.kt:67) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.utils.UtilsKt.temporaryProperties(Utils.kt:304) [utils-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.managers.Gradle.resolveDependencies(Gradle.kt:165) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:213) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at com.here.ort.analyzer.Analyzer$analyzeInParallel$$inlined$use$lambda$1$1$1.invokeSuspend(Analyzer.kt:143) [analyzer-0.1.0-SNAPSHOT.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.61.jar:1.3.61-release-180 (1.3.61)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [kotlinx-coroutines-core-1.3.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]

```

**Comment by sschuberth** [comment]
This simply looks like the cause being that the `tools.jar` property is not defined. Do you see it being defined somewhere?

But I recall that we already have some [special code](https://github.com/heremaps/oss-review-toolkit/blob/5740ef301a700d5d9768fd7257b9275f026885fc/analyzer/src/main/kotlin/managers/Maven.kt#L178) regarding `tools.jar`. I wonder if the issue goes away if you simply change the string in that line to `com.sun:tools:`. Would you mind giving that a try?

**Comment by CleanHit** [comment]
> com.sun:tools:

Do you mean that I have to change the `"jdk.tools:jdk.tools:"` to `com.sun:tools:` and run it again? If yes, then I'll might not be able to do it today since I'm running the scanner now and it will take some time to finish.

**Comment by CleanHit** [comment]
> This simply looks like the cause being that the `tools.jar` property is not defined. Do you see it being defined somewhere?
> 
> But I recall that we already have some [special code](https://github.com/heremaps/oss-review-toolkit/blob/5740ef301a700d5d9768fd7257b9275f026885fc/analyzer/src/main/kotlin/managers/Maven.kt#L178) regarding `tools.jar`. I wonder if the issue goes away if you simply change the string in that line to `com.sun:tools:`. Would you mind giving that a try?

Do you mean that I have to change the "jdk.tools:jdk.tools:" to com.sun:tools: and run it again? If yes, then I'll might not be able to do it today since I'm running the scanner now and it will take some time to finish.

**Comment by sschuberth** [comment]
> Do you mean that I have to change the `"jdk.tools:jdk.tools:"` to `"com.sun:tools:"` and run it again?

Yes. I've created a [PR](https://github.com/heremaps/oss-review-toolkit/pull/2275) for you to verify.

**Comment by CleanHit** [comment]
@sschuberth I've pulled the latest `Master` branch I'm still getting the same error using **openJDK 10.0.2** and now I'm also getting a lot of those kind of messages for different packages:

**New issue 1**
```bash
11:03:20.234 [analyzer-1] ERROR java.lang.Object - Unresolved: ModuleVersionResolveException: Could not resolve androidx.work:work-runtime:[2.1.0].
Caused by: ModuleVersionResolveException: Failed to list versions for androidx.work:work-runtime.
Caused by: ResourceException: Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/androidx/work/work-runtime/maven-metadata.xml.
Caused by: HttpRequestException: Could not HEAD 'https://dl.google.com/dl/android/maven2/androidx/work/work-runtime/maven-metadata.xml'.
Caused by: SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: SunCertPathBuilderException: unable to find valid certification path to requested target
```
My **analyzer-result.yml** is ~350MB big and has `has_issues: true` compared to the status before the `Master` branch pull (+ build) with ~587MB and `has_issues: false`

However, using **openJDK 12.0.2** still has the original reported issue regarding `${tools.jar}` with less issues form **New issue 1** kind. The **analyzer-result.yml** has ~587MB with `has_issues: false`.

**Comment by sschuberth** [comment]
Regarding the `ValidatorException` you see with OpenJDK 10.0.2: These errors look as if you are behind a corporate proxy that tampers with the certificates. Is that the case?

**Comment by CleanHit** [comment]
> Regarding the `ValidatorException` you see with OpenJDK 10.0.2: These errors look as if you are behind a corporate proxy that tampers with the certificates. Is that the case?

I'm not behind any proxy and I need to correct my self. With OpenJDK 12.0.2 I don't see any errors form type '**New issiue 1**'

**Comment by sschuberth** [comment]
Ok, but still the `cacerts` file from your OpenJDK 10.0.2 seems to be missing the certificates that allow you to download from `https://dl.google.com/`. [This post](https://stackoverflow.com/q/47323909/1127485) might help to resolve this.

So let's focus on the issues you see with OpenJDK 12.0.2 then. If you still see the `com.sun:tools:jar must specify an absolute path but is ${tools.jar}` error, that comes directly from Maven, not from ORT, and I believe you can ignore it in this case, esp. as you say that your `analyzer-result.yml` contains `has_issues: false`. So it should be good for ORT to process further with the scanner.

**Comment by CleanHit** [comment]
Ok, but since the ORT was tested with OpenJDK 10 I wanted to make the `ValidatorException` errors go away. So, for anyone else getting the same issue this is what I did under `Linux` for an Android project. The credit goes to this [SO post](changeit):

1. Download the certificate for `https://dl.google.com`:
```bash 
sudo openssl x509 -in <(openssl s_client -connect dl.google.com:443 -prexit 2>/dev/null) -out ~/<your_file_name>.crt 
```
1. Load the certificate into the `cacerts` database:
```bash
keytool -importcert -file ~/<your_file_name>.crt  -alias <give_some_name> -keystore <path_to_OpenJDK>/lib/security/cacerts -storepass (default: changeit)
```

**Comment by sschuberth** [comment]
So, issue closed? (BTW, your SO link is broken.)

**Comment by CleanHit** [comment]
> So, issue closed? (BTW, your SO link is broken.)

I've fixed the SO link. If the `com.sun:tools:jar must specify an absolute path but is ${tools.jar}` Warning is not a problem then it is closed :-).
