### ISSUE TITLE
Licensee scanner cannot found path to make a scan result file.

### ISSUE THREAD

**Issue by dd-lge** [heremaps/oss-review-toolkit#2316]
I used the licensee scanner in the below source code.
`https://github.com/simplejson/simplejson.git`

The licensee  worked well and generated a result file.
But the wrapper of ORT printed an error like below.
```
15:49:19.492 [main] DEBUG com.here.ort.utils.ProcessCapture -
Exception in thread "main" java.lang.IllegalArgumentException: this and base files have different roots: LICENSE.txt and /home/osc/scanner-test/json_test/source/Downloader/unknown/simplejson/unknown.
        at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:81)
        at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:92)
        at com.here.ort.scanner.LocalScanner.relativizePath(LocalScanner.kt:446)
        at com.here.ort.scanner.scanners.Licensee.generateSummary(Licensee.kt:145)
        at com.here.ort.scanner.scanners.Licensee.scanPath(Licensee.kt:121)
        at com.here.ort.scanner.LocalScanner.scanInputPath(LocalScanner.kt:375)
        at com.here.ort.commands.ScannerCommand.run(ScannerCommand.kt:185)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:139)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:221)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:218)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:236)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:259)
        at com.here.ort.OrtMainKt.main(OrtMain.kt:205)
```

It seems a path problem. Please fix this error.

**Comment by sschuberth** [comment]
Should have been fixed as part of https://github.com/heremaps/oss-review-toolkit/pull/2327, please verify with current `master` and eventually close this issue. Thanks!

**Comment by dd-lge** [comment]
I ran the current master and verified it to work well! Thank you for fixing it.
