### ISSUE TITLE
Error with npm 6.14.1

### ISSUE THREAD

**Issue by fb33** [heremaps/oss-review-toolkit#2329]
Hi, 

I use ORT with Docker on the master Branch.
Npm version has been updated to 6.14.1  (see commit 4cfb8fa290b1991df32c2ef7405e28ff8f15c910), so the image build works fine.

But now, the analyze phase failed with npm project : 
```
09:46:41  08:46:41.053 [main] INFO  com.here.ort.analyzer.Analyzer - NPM projects found in:
09:46:41  08:46:41.056 [main] INFO  com.here.ort.analyzer.Analyzer - 	package.json
09:46:41  08:46:41.132 [analyzer-1] INFO  com.here.ort.utils.ProcessCapture - Running 'npm --version' in '/'...
09:46:43  Exception in thread "main" java.io.IOException: Unsupported npm version 6.14.1 does not fulfill >=5.7.0 <6.14.0.
09:46:43  	at com.here.ort.utils.CommandLineTool$DefaultImpls.checkVersion(CommandLineTool.kt:128)
09:46:43  	at com.here.ort.analyzer.managers.Npm.checkVersion(Npm.kt:76)
09:46:43  	at com.here.ort.utils.CommandLineTool$DefaultImpls.checkVersion$default(CommandLineTool.kt:118)
09:46:43  	at com.here.ort.analyzer.managers.Npm.beforeResolution(Npm.kt:108)
09:46:43  	at com.here.ort.analyzer.PackageManager.resolveDependencies(PackageManager.kt:205)
09:46:43  	at com.here.ort.analyzer.Analyzer$analyzeInParallel$$inlined$use$lambda$1$1$1.invokeSuspend(Analyzer.kt:143)
09:46:43  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09:46:43  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
09:46:43  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:46:43  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:46:43  	at java.base/java.lang.Thread.run(Thread.java:834)
```

The Npm manager seems not to be updated : 
`override fun getVersionRequirement(): Requirement = Requirement.buildNPM("5.7.* - 6.13.*")`

Regards

**Comment by sschuberth** [comment]
Good point, thanks for reporting. While the fix in PR #2330 is still pending, you may want to work around this by passing the `--ignore-tool-versions` command line option to the Analyzer.

**Comment by fb33** [comment]
Hello, don't you think that files : `.appveyor.yml` and `.travis.yml` should also be align to npm 6.14.0 version ?

**Comment by sschuberth** [comment]
I do, that's why they are 😉 See https://github.com/heremaps/oss-review-toolkit/pull/2330/commits/b852212d27dd35256c05db1c7cc480ce076373e0.
